
const rootObj ={
    showChilds:true,
    level:0,
    folder1:{
        level:1,
        showChilds:true,
        folder11:{
            level:2,
            showChilds:true,
            folder111:{
                level:3,
                showChilds:true,
                folder1111:{},
                folder1112:{}
            },
            folder112:{
                level:3,
                showChilds:false,
                folder1121:{},
                folder1122:{}
            }
        },
        folder12:{
            level:2,
            showChilds:false,
            folder121:{
                level:3,
                showChilds:false,
                folder1211:{},
                folder1212:{}
            },
            folder122:{
                level:3,
                showChilds:false,
                folder1221:{},
                folder1222:{}
            }
        }
    },
    folder2:{
        level:1,
        showChilds:false,
        folder21:{
            level:2,
            showChilds:false,
            folder211:{
                level:3,
                showChilds:false,
                folder2111:{},
                folder2112:{}
            },
            folder212:{
                level:3,
                showChilds:false,
                folder2121:{},
                folder2122:{}
            }
        },
        folder22:{
            level:2,
            showChilds:false,
            folder221:{
                level:3,
                showChilds:false,
                folder2211:{},
                folder2212:{}
            },
            folder222:{
                level:3,
                showChilds:false,
                folder2221:{},
                folder2222:{}
            }
        }
    },
    folder3:{
        level:1,
        showChilds:false,
        folder31:{
            level:2,
            showChilds:false,
            folder311:{
                level:3,
                showChilds:false,
                folder3111:{},
                folder3112:{}
            },
            folder312:{
                level:2,
                showChilds:false,
                folder3121:{},
                folder3122:{}
            }
        },
        folder32:{
            level:2,
            showChilds:false,
            folder321:{
                level:3,
                showChilds:false,
                folder3211:{},
                folder3212:{}
            },
            folder322:{
                level:3,
                showChilds:false,
                folder3221:{},
                folder3222:{}
            }
        }
    },
    folder4:{
        level:1,
        showChilds:false,
        folder41:{
            level:2,
            showChilds:false,
            folder411:{
                level:3,
                showChilds:false,
                folder4111:{},
                folder4112:{}
            },
            folder412:{
                level:3,
                showChilds:false,
                folder4121:{},
                folder4122:{}
            }
        },
        folder42:{
            level:2,
            showChilds:false,
            folder421:{
                level:3,
                showChilds:false,
                folder4211:{},
                folder4212:{}
            },
            folder422:{
                level:3,
                showChilds:false,
                folder4221:{},
                folder4222:{}
            }
        }
    }
}

export default rootObj